worker_processes auto;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server_tokens off;

    client_body_temp_path /tmp/client_body_temp;
    proxy_temp_path       /tmp/proxy_temp;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    log_format ech '$remote_addr - [$time_local] "$request" $status '
                   'sni="$ssl_server_name" '
                   'ech_status="$ssl_ech_status" '
                   'ech_outer_sni="$ssl_ech_outer_server_name"';

    access_log /dev/stdout ech;
    error_log  /dev/stderr info;

    sendfile on;
    keepalive_timeout 30;

    ssl_protocols TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    include /etc/nginx/conf.d/*.conf;
}
